apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfserviceportal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selfserviceportal
  template:
    metadata:
      labels:
        app: selfserviceportal
    spec:
      containers:
      - name: selfserviceportal
        image: image-registry.openshift-image-registry.svc:5000/selfserviceportal/selfservice-portal:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          value: "Data Source=sqlserver,1433;Database=SelfServicePortalDb;User ID=sa;Password=Lcv195l6131!;Encrypt=False;TrustServerCertificate=True;"
---
apiVersion: v1
kind: Service
metadata:
  name: selfserviceportal
spec:
  selector:
    app: selfserviceportal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
